### ISSUE TITLE
TypeError: src is not a numpy array, neither a scalar

### ISSUE THREAD

**Issue by zorrocai** [hussaintamboli/python-image-to-text#2]
When I run the recognise.py, there happens a typeerror:
Traceback (most recent call last):
  File "recognise.py", line 105, in <module>
    print get_captcha_text_from_captcha_image("./test.jpg") 
  File "recognise.py", line 55, in get_captcha_text_from_captcha_image
    tif_file = preprocess_image_using_opencv(captcha_path)
  File "recognise.py", line 87, in preprocess_image_using_opencv
    bin_image_path = binarize_image_using_opencv(captcha_path)
  File "recognise.py", line 78, in binarize_image_using_opencv
    im_gray = cv2.cvtColor(captcha_path, 0)
TypeError: src is not a numpy array, neither a scalar

**Comment by hussaintamboli** [comment]
Thanks for reporting the issue. It was due to some changes I pushed some days ago without testing.

I have just fixed it.

**Comment by zorrocai** [comment]
Yeah, but there comes another value error:
Traceback (most recent call last):
  File "recognise.py", line 108, in <module>
    print get_captcha_text_from_captcha_image("test.jpg") 
  File "recognise.py", line 60, in get_captcha_text_from_captcha_image
    ocr_text = image_to_string(image, config="-psm 6")
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 130, in run_and_get_output
    temp_name, img_extension = save_image(image)
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/pytesseract/pytesseract.py", line 86, in save_image
    image.save(input_file_name, format=img_extension, **image.info)
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 1687, in save
    save_handler(self, fp, filename)
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 1363, in _save
    ifd[key] = im.encoderinfo[name]
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 491, in __setitem__
    self._setitem(tag, value, self.legacy_api)
  File "/home/zgluo/anaconda2/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 534, in _setitem
    dest[tag], = values
ValueError: too many values to unpack
Does it  caused by the version of PIL?

**Comment by hussaintamboli** [comment]
Did you follow installation instructions from my README? What version of PIL are you using?

**Comment by zorrocai** [comment]
Yes, the PIL version is the same as yours instruction.
And I just found that the ValueError is caused by the version of pytesseract. After I installed pytesseract 0.1.6 , the problem is gone.
Thanks for your attention ~~

**Comment by hussaintamboli** [comment]
Great! You can close the issue if this issue is fixed.
